version: '3.9'

services:
  nest_backend:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: nest_backend
    image: nest_backend:1.0
    
    volumes:
      - .:/anandu/src/app
      - /anandu/src/app/node_modules
    depends_on:
      - postgres
    environment:
      DB_URL: postgres://postgres:postgres@postgres:5432/postgres
      PORT: 3000
    ports:
      - "8080:3000"
    networks:
      - node-network
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "35000:5432"
    networks:
      - node-network
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - node-network

networks:
  node-network:
    driver: bridge